apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ${{ values.appName }}-staging

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: ${{ values.appName }}-frontend
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2

  - target:
      kind: Deployment
      name: ${{ values.appName }}-backend
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2

  - target:
      kind: Cluster
      name: ${{ values.appName }}-db
    patch: |
      - op: replace
        path: /spec/instances
        value: 2
      - op: replace
        path: /spec/storage/size
        value: 5Gi

  - target:
      kind: Ingress
      name: ${{ values.appName }}-frontend
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: ${{ values.appName }}-staging.${{ values.ingressDomain }}
  - target:
      kind: Ingress
      name: ${{ values.appName }}-backend
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: api.${{ values.appName }}-staging.${{ values.ingressDomain }}
