apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.docName }}
  title: ${{ values.title }}
  description: ${{ values.description }}
  annotations:
    engineering-hub/repo: ${{ values.repoOrg }}/${{ values.repoName }}
    engineering-hub/branch: ${{ values.branch }}
    engineering-hub/content-base: ${{ values.contentBase }}
    github.com/project-slug: ${{ values.repoOrg }}/${{ values.repoName }}
    backstage.io/source-location: url:https://github.com/${{ values.repoOrg }}/${{ values.repoName }}
  links:
    - url: https://github.com/${{ values.repoOrg }}/${{ values.repoName }}
      title: GitHub Repository
      icon: github
spec:
  type: documentation
  lifecycle: production
  owner: ${{ values.owner }}
