apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ values.appName }}-frontend
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: ${{ values.appName }}.${{ values.ingressDomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${{ values.appName }}-frontend
                port:
                  number: 80
