apiVersion: v1
kind: Service
metadata:
  name: ${{ values.appName }}-frontend
spec:
  selector:
    app: ${{ values.appName }}-frontend
  ports:
    - port: 80
      targetPort: ${{ values.frontendPort }}
