apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-docs
  description: Documentation for Stratpoint Backstage
  annotations:
    backstage.io/techdocs-ref: dir:./content
spec:
  type: documentation
  lifecycle: production
  owner: backstage-admins
